#!/usr/bin/env python3
"""Parse swift symbol-graph JSON emitted by api-baseline.sh into a stable,
sorted, diffable text report.

See the header comment in Scripts/api-baseline.sh for the extraction
methodology and its documented under/over-counts. This file only formats
what that script already decided to include: public (or open) symbols that
carry a `location` (i.e. an explicit declaration in this repository's
Sources/ tree).

Invoked with three environment variables (see api-baseline.sh):
  REPO_ROOT         absolute path to the repo root
  SYMBOL_GRAPH_DIR  directory containing *.symbols.json files
  TARGETS           space-separated list of first-party scheme/module names
"""
import collections
import glob
import json
import os
import sys

REPO_ROOT = os.environ["REPO_ROOT"]
SYMBOL_GRAPH_DIR = os.environ["SYMBOL_GRAPH_DIR"]
TARGETS = os.environ["TARGETS"].split()

TYPE_KINDS = {"class", "struct", "enum", "protocol", "typealias"}


def domain_for(relpath, target):
    """Bucket a source file into a top-level domain for the summary table.

    For the default SwapFoundationKit target this is the first directory
    under Sources/SwapFoundationKit/ (Core, UI, Services, ...). For other
    targets it is the target name itself, since those targets are not yet
    subdivided.
    """
    parts = relpath.split("/")
    prefix = ("Sources", target)
    if tuple(parts[:2]) == prefix:
        if len(parts) > 3:
            return parts[2]
        return "(root)"
    return target


def collect_rows():
    rows = []
    for target in TARGETS:
        files = sorted(glob.glob(os.path.join(SYMBOL_GRAPH_DIR, f"{target}.symbols.json")))
        files += sorted(glob.glob(os.path.join(SYMBOL_GRAPH_DIR, f"{target}@*.symbols.json")))
        for fp in files:
            with open(fp) as f:
                data = json.load(f)
            for sym in data.get("symbols", []):
                if sym.get("accessLevel") not in ("public", "open"):
                    continue
                loc = sym.get("location")
                if not loc:
                    continue
                uri = loc.get("uri", "")
                if not uri.startswith("file://"):
                    continue
                path = uri[len("file://"):]
                if not path.startswith(REPO_ROOT):
                    continue
                relpath = os.path.relpath(path, REPO_ROOT)
                if not relpath.startswith("Sources/"):
                    continue
                line = loc.get("position", {}).get("line", 0) + 1
                kind = sym["kind"]["identifier"].replace("swift.", "")
                sympath = ".".join(sym.get("pathComponents", []))
                access = sym.get("accessLevel", "")
                rows.append((target, relpath, line, kind, sympath, access))
    # De-duplicate: a generic iOS Simulator destination compiles more than
    # one architecture; both write the same symbol-graph directory, so a
    # symbol may be observed twice with identical fields. Keep one.
    return sorted(set(rows), key=lambda r: (r[0], r[1], r[2], r[4], r[3]))


def write_report(rows):
    out = sys.stdout

    out.write("# SwapFoundationKit API baseline\n")
    out.write("#\n")
    out.write("# Generated by Scripts/api-baseline.sh — do not hand-edit.\n")
    out.write("# Methodology and known under/over-counts are documented in that\n")
    out.write("# script's header and in Docs/development/v4-api-ledger.md.\n")
    out.write("# This file intentionally has no timestamp: it must be\n")
    out.write("# byte-identical across runs for an unchanged source tree.\n")
    out.write("#\n")

    out.write("## SUMMARY\n#\n")

    by_target_decls = collections.Counter(r[0] for r in rows)
    by_target_types = collections.Counter(r[0] for r in rows if r[3] in TYPE_KINDS and "." not in r[4])

    out.write("# Per-target totals (declarations = all public, located symbols;\n")
    out.write("# types = top-level class/struct/enum/protocol/typealias only):\n")
    out.write(f"#   {'target':<34} {'declarations':>12} {'types':>8}\n")
    for target in TARGETS:
        out.write(f"#   {target:<34} {by_target_decls.get(target, 0):>12} {by_target_types.get(target, 0):>8}\n")
    out.write("#\n")

    default_target = "SwapFoundationKit"
    default_rows = [r for r in rows if r[0] == default_target]
    dom_decls = collections.Counter(domain_for(r[1], default_target) for r in default_rows)
    dom_types = collections.Counter(
        domain_for(r[1], default_target)
        for r in default_rows
        if r[3] in TYPE_KINDS and "." not in r[4]
    )
    out.write(f"# {default_target} — per-domain breakdown (public declarations / top-level public types):\n")
    out.write(f"#   {'domain':<20} {'declarations':>12} {'types':>8}\n")
    for dom in sorted(dom_decls, key=lambda d: -dom_decls[d]):
        out.write(f"#   {dom:<20} {dom_decls[dom]:>12} {dom_types.get(dom, 0):>8}\n")
    out.write("#\n")

    kind_counts = collections.Counter(r[3] for r in default_rows)
    out.write(f"# {default_target} — declarations by kind:\n")
    for kind in sorted(kind_counts, key=lambda k: -kind_counts[k]):
        out.write(f"#   {kind:<20} {kind_counts[kind]:>6}\n")
    out.write("#\n")

    out.write("## SYMBOLS\n")
    out.write("# target | kind | file:line | symbol\n")
    for target, relpath, line, kind, sympath, access in rows:
        out.write(f"{target} | {kind} | {relpath}:{line} | {sympath}\n")


def main():
    rows = collect_rows()
    write_report(rows)


if __name__ == "__main__":
    main()
