name: Package CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-package:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest]
        swift-version: ['6.2']
    
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
    
    - name: Build Package
      run: swift build -v
    
    - name: Run Tests
      run: swift test -v
    
    - name: Build for Release
      run: swift build -c release -v
    
    - name: Validate Package
      run: swift package validate
